In [1]:
import pandas as pd
import numpy as np
import glob
from sklearn.feature_selection import SelectKBest, chi2
from trainer import train_evaluate

In [3]:
def get_data(files):
    data_matrix = np.loadtxt(files[0], dtype='i', delimiter='\t')
    data_matrix = data_matrix.T

    last_col = [0] * len(data_matrix)
    data_matrix = np.column_stack((data_matrix, last_col))

    for x in range(len(files) - 1):
        temp_matrix = np.loadtxt(files[x + 1], dtype='i', delimiter='\t')
        temp_matrix = temp_matrix.T
        last_col = [x+1] * len(temp_matrix)
        temp_matrix = np.column_stack((temp_matrix, last_col))
        data_matrix = np.concatenate((data_matrix, temp_matrix), axis=0)

    X = data_matrix[:, :-1]
    Y = data_matrix[:, -1]
    return X, Y

In [5]:
files = glob.glob('dataset/*.txt')
X, Y = get_data(files)

fvalue_selector = SelectKBest(chi2, k=10)
fvalue_selector.fit(X, Y)

rank = fvalue_selector.scores_
top_rank = []
indexes = rank.argsort()[-10:][::-1]

for index in indexes:
    top_rank.append(rank[index])
    

In [ ]:
layer_sizes = [200,350,500]
momentum_values = [0, 0.9]
filename = "resultaty.csv"

In [11]:
results = pd.DataFrame(columns=["layer_size","momentum_value","feature_number","score","confusion_matrix"])

for layer_size in layer_sizes:
    for momentum_value in momentum_values:
        for feature_number in range(15,16):
            to_train = indexes[:feature_number]
            
            score, matrix = train_evaluate(X=X[:, to_train], Y=Y,
                                           momentum_value=momentum_value, layer_size=layer_size)
            
            results = results.append({"layer_size":layer_size,"momentum_value":momentum_value,"feature_number":feature_number,
                                      "score":score,"confusion_matrix":matrix}, ignore_index=True)
results.to_csv(filename)

wszedlem do funkcji
Kolejny fold
Score:0.25055432372505543
Matrix:[[ 2 15 10  0  7]
 [ 8 29 27  0  7]
 [ 1 25 64  0 25]
 [ 0 89  0  0 43]
 [17 46 18  0 18]]
Kolejny fold
Score:0.3511111111111111
Matrix:[[  0   0   0  22  12]
 [  0   0   0  46  25]
 [  0   2   0  46  67]
 [  0   0   0 130   1]
 [  0   1   0  70  28]]
Kolejny fold
Score:0.21951219512195122
Matrix:[[  0   0   0   0  34]
 [  0   0   0   0  71]
 [  0   0   0   0 115]
 [  0   0   0   0 132]
 [  0   0   0   0  99]]
Kolejny fold
Score:0.32666666666666666
Matrix:[[  0   0   2  32   0]
 [  0   0   3  68   0]
 [  0   0  16  99   0]
 [  0   0   0 131   0]
 [  0   0   2  97   0]]
Kolejny fold
Score:0.516629711751663
Matrix:[[  0   0  26   8   0]
 [  0   0  54  17   0]
 [  0   0 108   7   0]
 [  0   0   7 125   0]
 [  0   0  62  37   0]]
Kolejny fold
Score:0.24
Matrix:[[  0   4  30   0   0]
 [  0   6  65   0   0]
 [  0  14 101   0   0]
 [  0   1 127   1   2]
 [  0   2  97   0   0]]
Kolejny fold
Score:0.3902439024390244
Matrix:[[  0 